defaults:
  - refold: alphafold3
  - inversefold: InverseFold_nbl
  - metrics: nuc_binding_ligand

design_dir: /home/nvme04/qtfeng/design/benchmark/dev/20251231/ODesign_benchmark/examples/ODesign/nuc_binding_ligand
root: results
gpus: 0
# gpus: 0,1,2,3,4,5,6,7