res_dir: ./results
ex_name: debug
dataset: DNA
dataname: DNA
model_name: ODesign
lr: 0.001
lr_scheduler: onecycle
offline: 0
seed: 111
use_auxliary_data: 0
pretrained_path: ''
batch_size: 8
num_workers: 8
min_length: 40
epoch: 50
augment_eps: 0.0
geo_layer: 3
attn_layer: 3
node_layer: 3
edge_layer: 3
encoder_layer: 12
hidden_dim: 128
dropout: 0.0
k_neighbors: 30
virtual_frame_num: 8
virtual_atom_num: 3
mask_rate: 0.1
steps_per_epoch: 7006